import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles, Download, Loader2, CheckCircle2, X,
  FileText, Home, Calendar, DollarSign, Zap, Users, Cigarette,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface ContractGeneratorProps {
  onClose: () => void;
}

const tips = [
  { icon: Home, text: "Include property details — address, type, and features" },
  { icon: DollarSign, text: "Specify rent amount and payment due date" },
  { icon: Calendar, text: "Define lease duration and exact start date" },
  { icon: FileText, text: "Mention security deposit requirements" },
  { icon: Zap, text: "Outline utility responsibilities (water, power, internet)" },
  { icon: Users, text: "State policies on guests, pets, and subletting" },
];

const ContractGenerator = ({ onClose }: ContractGeneratorProps) => {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [contractGenerated, setContractGenerated] = useState(false);
  const { toast } = useToast();

  const generateContract = async () => {
    if (!prompt.trim()) {
      toast({
        variant: "destructive",
        title: "Input required",
        description: "Please describe your rental terms and conditions.",
      });
      return;
    }
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setContractGenerated(true);
      toast({ title: "Contract Generated", description: "Your rental agreement is ready to download." });
    }, 3000);
  };

  const downloadContract = () => {
    try {
      const content = `RENTAL AGREEMENT

THIS RENTAL AGREEMENT ("Agreement") is made and entered into this ${new Date().toLocaleDateString()}, by and between Property Owner ("Landlord") and Tenant.

PROPERTY: ${prompt.substring(0, 200)}...

TERM: This Agreement shall commence on ${new Date().toLocaleDateString()} and continue for the agreed lease term.

RENT: Tenant shall pay to Landlord the agreed monthly rent as described in the contract terms.

UTILITIES: Tenant shall be responsible for the payment of all utilities and services to the Property unless otherwise stated.

MAINTENANCE: Tenant shall maintain the Property in a clean and sanitary condition.

---
Generated by Nyumba Yo AI Contract Generator
Based on your specifications provided on ${new Date().toLocaleDateString()}`;

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `rental_agreement_${Date.now()}.txt`;
      document.body.appendChild(link);
      link.click();
      setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(link); }, 100);
      toast({ title: "Downloaded", description: "Contract saved to your device." });
    } catch {
      toast({ variant: "destructive", title: "Download Failed", description: "Please try again." });
    }
  };

  const reset = () => {
    setContractGenerated(false);
    setPrompt('');
  };

  return (
    <div className="flex flex-col w-full max-h-[85vh]">
      {/* Header */}
      <div className="bg-gradient-to-r from-[#0F172A] to-[#1D4ED8] px-6 py-5 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/15">
            <Sparkles className="h-5 w-5 text-white" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white">AI Contract Generator</h2>
            <p className="text-[11px] text-blue-200/80">Describe your terms — we'll draft the agreement</p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10 hover:bg-white/20 text-white transition-colors"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto">
        <AnimatePresence mode="wait">
          {!contractGenerated ? (
            <motion.div
              key="form"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.2 }}
              className="p-6 space-y-5"
            >
              {/* Prompt textarea */}
              <div>
                <label className="block text-xs font-semibold uppercase tracking-wider text-[#64748B] mb-2">
                  Describe your rental terms and conditions
                </label>
                <div className="relative">
                  <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    rows={7}
                    placeholder={`Example: This is a 12-month lease agreement for a 2-bedroom apartment at 123 Main Street. The monthly rent is $1,200 with a security deposit of $1,200. Utilities are not included. No pets allowed. Rent is due on the 1st of each month...`}
                    className="w-full rounded-xl border border-[#E2E8F0] bg-white px-4 py-3 text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#1D4ED8] focus:ring-2 focus:ring-[#1D4ED8]/10 transition-colors resize-none leading-relaxed"
                  />
                  <div className="absolute bottom-3 right-3 text-[11px] text-[#94A3B8]">
                    {prompt.length} chars
                  </div>
                </div>
              </div>

              {/* Tips grid */}
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-[#64748B] mb-3">
                  Tips for effective contract generation
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {tips.map(({ icon: Icon, text }) => (
                    <div
                      key={text}
                      className="flex items-start gap-2.5 rounded-lg border border-[#E2E8F0] bg-slate-50/70 px-3 py-2.5"
                    >
                      <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-[#1D4ED8]/10 mt-0.5">
                        <Icon className="h-3.5 w-3.5 text-[#1D4ED8]" />
                      </div>
                      <span className="text-xs text-[#64748B] leading-relaxed">{text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="success"
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="flex flex-col items-center justify-center py-14 px-8 text-center gap-5"
            >
              <div className="relative">
                <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-emerald-50 border border-emerald-100">
                  <CheckCircle2 className="h-10 w-10 text-emerald-500" />
                </div>
                <div className="absolute -top-2 -right-2 flex h-7 w-7 items-center justify-center rounded-full bg-[#1D4ED8]">
                  <Sparkles className="h-3.5 w-3.5 text-white" />
                </div>
              </div>

              <div className="space-y-2 max-w-sm">
                <h3 className="text-xl font-bold text-[#0F172A]">Contract Ready!</h3>
                <p className="text-sm text-[#64748B] leading-relaxed">
                  Your rental agreement has been generated based on your specifications. Download it as a text file or generate a new one.
                </p>
              </div>

              {/* Preview card */}
              <div className="w-full max-w-md rounded-xl border border-[#E2E8F0] bg-slate-50 p-4 text-left">
                <div className="flex items-center gap-2 mb-2">
                  <FileText className="h-4 w-4 text-[#1D4ED8]" />
                  <span className="text-xs font-semibold text-[#0F172A]">rental_agreement.txt</span>
                </div>
                <p className="text-xs text-[#64748B] line-clamp-3 leading-relaxed">
                  {prompt.substring(0, 150)}{prompt.length > 150 ? '…' : ''}
                </p>
                <div className="mt-2 flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 border border-emerald-100 px-2 py-0.5 text-[10px] font-medium text-emerald-700">
                    <CheckCircle2 className="h-3 w-3" /> AI Generated
                  </span>
                  <span className="text-[10px] text-[#94A3B8]">{new Date().toLocaleDateString()}</span>
                </div>
              </div>

              <button
                onClick={reset}
                className="text-xs text-[#1D4ED8] hover:underline"
              >
                Generate another contract
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Footer */}
      <div className="shrink-0 flex items-center justify-between border-t border-[#E2E8F0] px-6 py-4 bg-white">
        <button
          onClick={onClose}
          className="rounded-lg border border-[#E2E8F0] bg-white px-4 py-2 text-sm font-medium text-[#64748B] hover:bg-slate-50 transition-colors"
        >
          Close
        </button>

        {!contractGenerated ? (
          <button
            onClick={generateContract}
            disabled={isGenerating || !prompt.trim()}
            className="inline-flex items-center gap-2 rounded-lg bg-[#1D4ED8] px-5 py-2 text-sm font-semibold text-white hover:bg-[#1e40af] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate Contract
              </>
            )}
          </button>
        ) : (
          <button
            onClick={downloadContract}
            className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-5 py-2 text-sm font-semibold text-white hover:bg-emerald-700 transition-colors"
          >
            <Download className="h-4 w-4" />
            Download Contract
          </button>
        )}
      </div>
    </div>
  );
};

export default ContractGenerator;
